# Generated by Django 3.2.7 on 2021-09-15 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('status', '0001_initial'),
        ('prontuarios', '0001_initial'),
        ('funcionario', '0002_auto_20210915_0140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_mov', models.DateField()),
                ('num_pront', models.ManyToManyField(to='prontuarios.Prontuario')),
                ('st', models.ManyToManyField(to='status.Status')),
                ('usu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='funcionario.funcionario')),
            ],
        ),
    ]
