# Generated by Django 3.2.7 on 2021-09-15 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0002_unidades_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='unid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='unidades.unidades'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
    ]
